import os
import sys

# Import shared tree generator
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from tree_gen.tree_gen import generate_simple_tree, get_tree_stats

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

KNOWLEDGE_DIR = '.agents/knowledge'


def check_scope_write(write_target):
    """Block if write target is outside allowed scope (security gate, fail-closed)."""
    import json
    # Ensure .agents/skills is in sys.path so scope_guardian can be found
    _SKILLS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # -> .agents/skills
    if _SKILLS not in sys.path:
        sys.path.insert(0, _SKILLS)
    from scope_guardian.scripts.scope_check import is_file_in_scope

    lock_file = os.path.join(os.getcwd(), '.agents', 'scope_lock.json')
    if not os.path.exists(lock_file):
        print("[BLOCKED] scope_lock.json not found in .agents/. Create it first to define scope.")
        sys.exit(1)
    try:
        with open(lock_file, 'r', encoding='utf-8') as f:
            scope_data = json.load(f)
    except Exception:
        print("[BLOCKED] Failed to parse scope_lock.json.")
        sys.exit(1)
    allowed_files = scope_data.get('allowed_files', [])
    allowed_patterns = scope_data.get('allowed_patterns', [])
    task = scope_data.get('task', 'Unknown task')
    if not is_file_in_scope(write_target, allowed_files, allowed_patterns):
        print(f"[BLOCKED] Write target is OUT OF SCOPE.")
        print(f"Task: {task}")
        print(f"Target: {write_target}")
        print(f"Allowed: {allowed_files}")
        sys.exit(1)

def main():
    apply_mode = "--apply" in sys.argv

    target_dir = os.getcwd()
    knowledge_path = os.path.join(target_dir, KNOWLEDGE_DIR)
    structure_file = os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md')
    patterns_file = os.path.join(knowledge_path, 'COMMON_PATTERNS.md')

    # Check scope for each write target (file-level, not directory)
    check_scope_write(structure_file)
    check_scope_write(patterns_file)

    # Generate tree using shared module
    tree = generate_simple_tree(target_dir, max_depth=0)  # 0 = unlimited

    # Get stats
    stats = get_tree_stats(target_dir)

    struct_content = "# 🗺️ Project Structure Map\n\n"
    struct_content += "This map was automatically generated by `context_mapper.py`.\n"
    struct_content += "AI agents must read this file upon entering the project to grasp the architecture.\n\n"
    struct_content += "## Stats\n"
    struct_content += f"- Files: {stats['total_files']}\n"
    struct_content += f"- Directories: {stats['total_dirs']}\n"
    struct_content += f"- Max Depth: {stats['max_depth']}\n\n"
    struct_content += "## Structure\n"
    struct_content += "```text\n"
    struct_content += f"📁 {os.path.basename(target_dir)}/\n"
    struct_content += tree
    struct_content += "```\n"

    patterns_path = os.path.join(knowledge_path, 'COMMON_PATTERNS.md')
    patterns_content = ""
    if not os.path.exists(patterns_path):
        patterns_content = "# 🧩 Common Patterns & Conventions\n\n"
        patterns_content += "This file contains the fundamental rules of the project. The AI MUST read this file before writing code.\n\n"
        patterns_content += "## 1. Architecture\n"
        patterns_content += "- Document architecture conventions here (e.g. all APIs are in `src/services`).\n\n"
        patterns_content += "## 2. Code Style\n"
        patterns_content += "- Document styling rules here (e.g. no Tailwind, use Vanilla CSS).\n\n"
        patterns_content += "## 3. Security\n"
        patterns_content += "- Never store credentials in code. Always use `.env`.\n"

    if not apply_mode:
        print("[DRY-RUN MODE] Context Mapper Preview")
        print("=" * 50)
        print(f"Target File: {os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md')}")
        print("--- Content Preview ---")
        print(struct_content[:500] + "\n... (truncated)")
        if patterns_content:
            print(f"\nTarget File: {patterns_path}")
            print("--- Content Preview ---")
            print(patterns_content[:200] + "\n... (truncated)")
        print("=" * 50)
        print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
        print('"Pratinjau berhasil. Silakan jalankan ulang perintah dengan tambahan flag --apply untuk menyimpan perubahan ini ke dalam disk."')
    else:
        os.makedirs(knowledge_path, exist_ok=True)
        with open(os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md'), 'w', encoding='utf-8') as f:
            f.write(struct_content)

        if patterns_content:
            with open(patterns_path, 'w', encoding='utf-8') as f:
                f.write(patterns_content)

        print(f"[OK] Knowledge Catalog berhasil dibuat/diperbarui di folder `{KNOWLEDGE_DIR}/`.")
        print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
        print('"Mulai sekarang, setiap kali Anda menangani proyek ini, tolong panggil view_file pada .agents/knowledge/PROJECT_STRUCTURE.md dan .agents/knowledge/COMMON_PATTERNS.md terlebih dahulu sebelum melakukan pencarian atau menulis kode."')

if __name__ == "__main__":
    main()
