import os
import sys

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

IGNORE_DIRS = {'node_modules', '.git', 'vendor', 'dist', 'build', '.history', 'quarantine', '.backup_replace'}
KNOWLEDGE_DIR = '.agents/knowledge'

def generate_tree(dir_path, prefix=""):
    tree_str = ""
    try:
        entries = sorted(os.listdir(dir_path))
    except Exception:
        return ""
        
    entries = [e for e in entries if e not in IGNORE_DIRS]
    for i, entry in enumerate(entries):
        path = os.path.join(dir_path, entry)
        is_last = (i == len(entries) - 1)
        connector = "└── " if is_last else "├── "
        
        if os.path.isdir(path):
            tree_str += f"{prefix}{connector}📁 {entry}/\n"
            extension = "    " if is_last else "│   "
            tree_str += generate_tree(path, prefix + extension)
        else:
            if not entry.startswith('.'):
                tree_str += f"{prefix}{connector}📄 {entry}\n"
    return tree_str

def main():
    apply_mode = "--apply" in sys.argv
    
    target_dir = os.getcwd()
    knowledge_path = os.path.join(target_dir, KNOWLEDGE_DIR)
    
    struct_path = os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md')
    tree = generate_tree(target_dir)
    
    struct_content = "# 🗺️ Project Structure Map\n\n"
    struct_content += "This map was automatically generated by `context_mapper.py`. AI agents must read this file upon entering the project to grasp the architecture without scanning the whole folder.\n\n"
    struct_content += "```text\n"
    struct_content += f"📁 {os.path.basename(target_dir)}/\n"
    struct_content += tree
    struct_content += "```\n"

    patterns_path = os.path.join(knowledge_path, 'COMMON_PATTERNS.md')
    patterns_content = ""
    if not os.path.exists(patterns_path):
        patterns_content = "# 🧩 Common Patterns & Conventions\n\n"
        patterns_content += "This file contains the fundamental rules of the project. The AI MUST read this file before writing code.\n\n"
        patterns_content += "## 1. Architecture\n- Document architecture conventions here (e.g. all APIs are in `src/services`).\n\n"
        patterns_content += "## 2. Code Style\n- Document styling rules here (e.g. no Tailwind, use Vanilla CSS).\n\n"
        patterns_content += "## 3. Security\n- Never store credentials in code. Always use `.env`.\n"

    if not apply_mode:
        print("[DRY-RUN MODE] Context Mapper Preview")
        print("=" * 50)
        print(f"Target File: {struct_path}")
        print("--- Content Preview ---")
        print(struct_content[:500] + "\n... (truncated)")
        if patterns_content:
            print(f"\nTarget File: {patterns_path}")
            print("--- Content Preview ---")
            print(patterns_content[:200] + "\n... (truncated)")
        print("=" * 50)
        print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
        print('"Pratinjau berhasil. Silakan jalankan ulang perintah dengan tambahan flag --apply untuk menyimpan perubahan ini ke dalam disk."')
    else:
        os.makedirs(knowledge_path, exist_ok=True)
        with open(struct_path, 'w', encoding='utf-8') as f:
            f.write(struct_content)
            
        if patterns_content:
            with open(patterns_path, 'w', encoding='utf-8') as f:
                f.write(patterns_content)
                
        print(f"[OK] Knowledge Catalog berhasil dibuat/diperbarui di folder `{KNOWLEDGE_DIR}/`.")
        print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
        print('"Mulai sekarang, setiap kali Anda menangani proyek ini, tolong panggil view_file pada .agents/knowledge/PROJECT_STRUCTURE.md dan COMMON_PATTERNS.md terlebih dahulu sebelum melakukan pencarian atau menulis kode."')

if __name__ == "__main__":
    main()
