import os
import sys

# Import shared tree generator
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from tree_gen.tree_gen import generate_simple_tree, get_tree_stats

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

KNOWLEDGE_DIR = '.agents/knowledge'

def main():
    apply_mode = "--apply" in sys.argv

    target_dir = os.getcwd()
    knowledge_path = os.path.join(target_dir, KNOWLEDGE_DIR)

    # Generate tree using shared module
    tree = generate_simple_tree(target_dir, max_depth=0)  # 0 = unlimited

    # Get stats
    stats = get_tree_stats(target_dir)

    struct_content = "# 🗺️ Project Structure Map\n\n"
    struct_content += "This map was automatically generated by `context_mapper.py`.\n"
    struct_content += "AI agents must read this file upon entering the project to grasp the architecture.\n\n"
    struct_content += "## Stats\n"
    struct_content += f"- Files: {stats['total_files']}\n"
    struct_content += f"- Directories: {stats['total_dirs']}\n"
    struct_content += f"- Max Depth: {stats['max_depth']}\n\n"
    struct_content += "## Structure\n"
    struct_content += "```text\n"
    struct_content += f"📁 {os.path.basename(target_dir)}/\n"
    struct_content += tree
    struct_content += "```\n"

    patterns_path = os.path.join(knowledge_path, 'COMMON_PATTERNS.md')
    patterns_content = ""
    if not os.path.exists(patterns_path):
        patterns_content = "# 🧩 Common Patterns & Conventions\n\n"
        patterns_content += "This file contains the fundamental rules of the project. The AI MUST read this file before writing code.\n\n"
        patterns_content += "## 1. Architecture\n"
        patterns_content += "- Document architecture conventions here (e.g. all APIs are in `src/services`).\n\n"
        patterns_content += "## 2. Code Style\n"
        patterns_content += "- Document styling rules here (e.g. no Tailwind, use Vanilla CSS).\n\n"
        patterns_content += "## 3. Security\n"
        patterns_content += "- Never store credentials in code. Always use `.env`.\n"

    if not apply_mode:
        print("[DRY-RUN MODE] Context Mapper Preview")
        print("=" * 50)
        print(f"Target File: {os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md')}")
        print("--- Content Preview ---")
        print(struct_content[:500] + "\n... (truncated)")
        if patterns_content:
            print(f"\nTarget File: {patterns_path}")
            print("--- Content Preview ---")
            print(patterns_content[:200] + "\n... (truncated)")
        print("=" * 50)
        print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
        print('"Pratinjau berhasil. Silakan jalankan ulang perintah dengan tambahan flag --apply untuk menyimpan perubahan ini ke dalam disk."')
    else:
        os.makedirs(knowledge_path, exist_ok=True)
        with open(os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md'), 'w', encoding='utf-8') as f:
            f.write(struct_content)

        if patterns_content:
            with open(patterns_path, 'w', encoding='utf-8') as f:
                f.write(patterns_content)

        print(f"[OK] Knowledge Catalog berhasil dibuat/diperbarui di folder `{KNOWLEDGE_DIR}/`.")
        print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
        print('"Mulai sekarang, setiap kali Anda menangani proyek ini, tolong panggil view_file pada .agents/knowledge/PROJECT_STRUCTURE.md dan .agents/knowledge/COMMON_PATTERNS.md terlebih dahulu sebelum melakukan pencarian atau menulis kode."')

if __name__ == "__main__":
    main()
