import os
import sys

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

IGNORE_DIRS = {'node_modules', '.git', 'vendor', 'dist', 'build', '.history', 'quarantine', '.backup_replace'}
KNOWLEDGE_DIR = '.agents/knowledge'

def generate_tree(dir_path, prefix=""):
    tree_str = ""
    try:
        entries = sorted(os.listdir(dir_path))
    except Exception:
        return ""
        
    entries = [e for e in entries if e not in IGNORE_DIRS]
    for i, entry in enumerate(entries):
        path = os.path.join(dir_path, entry)
        is_last = (i == len(entries) - 1)
        connector = "└── " if is_last else "├── "
        
        if os.path.isdir(path):
            tree_str += f"{prefix}{connector}📁 {entry}/\n"
            extension = "    " if is_last else "│   "
            tree_str += generate_tree(path, prefix + extension)
        else:
            if not entry.startswith('.'):
                tree_str += f"{prefix}{connector}📄 {entry}\n"
    return tree_str

def main():
    target_dir = os.getcwd()
    knowledge_path = os.path.join(target_dir, KNOWLEDGE_DIR)
    
    os.makedirs(knowledge_path, exist_ok=True)
    
    struct_path = os.path.join(knowledge_path, 'PROJECT_STRUCTURE.md')
    tree = generate_tree(target_dir)
    
    with open(struct_path, 'w', encoding='utf-8') as f:
        f.write("# 🗺️ Project Structure Map\n\n")
        f.write("This map was automatically generated by `context_mapper.py`. AI agents must read this file upon entering the project to grasp the architecture without scanning the whole folder.\n\n")
        f.write("```text\n")
        f.write(f"📁 {os.path.basename(target_dir)}/\n")
        f.write(tree)
        f.write("```\n")

    patterns_path = os.path.join(knowledge_path, 'COMMON_PATTERNS.md')
    if not os.path.exists(patterns_path):
        with open(patterns_path, 'w', encoding='utf-8') as f:
            f.write("# 🧩 Common Patterns & Conventions\n\n")
            f.write("This file contains the fundamental rules of the project. The AI MUST read this file before writing code.\n\n")
            f.write("## 1. Architecture\n- Document architecture conventions here (e.g. all APIs are in `src/services`).\n\n")
            f.write("## 2. Code Style\n- Document styling rules here (e.g. no Tailwind, use Vanilla CSS).\n\n")
            f.write("## 3. Security\n- Never store credentials in code. Always use `.env`.\n")

    print(f"[OK] Knowledge Catalog berhasil dibuat/diperbarui di folder `{KNOWLEDGE_DIR}/`.")
    print("\n💡 PROMPT UNTUK AI (Copy-Paste ini):")
    print('"Mulai sekarang, setiap kali Anda menangani proyek ini, tolong panggil view_file pada .agents/knowledge/PROJECT_STRUCTURE.md dan COMMON_PATTERNS.md terlebih dahulu sebelum melakukan pencarian atau menulis kode."')

if __name__ == "__main__":
    main()
